Catkin-ProjectName: object_recognition_transparent_objects
Version: 0.2.3
Description: A technique to recognize transparent objects

Author: Ilya, Vincent Rabaud <vrabaud@willowgarage.com>
Maintainer:  Vincent Rabaud <vrabaud@willowgarage.com>
Homepage:  http://ecto.willowgarage.com

Depends: catkin, ecto, object_recognition_core

Catkin-CopyrightType:  willowgarage
Catkin-DebRulesType: cmake
